### ISSUE TITLE
Switching between 5V and 12V fan supply

### ISSUE THREAD

**Issue by DeepCoreSystem** [SasaKaranovic/OpenFan-Micro#2]
Hi there!

I found your project through hackster.io because I was looking for some ideas about an ESPHome fan controller.

I opened the schematic and PCB in KiCad, but I can't figure out how you perform the switching between 5V and 12V for the fan supply. I see that you use GPIO 0 to control the enable pin of the DC/DC boost IC.

But even with the datasheet of the MIC2290, I don't understand how disabling the DC/DC converter should deliver 5V to the fan. A low on the DC/DC Enable pin should disable the boost converter, thus delivering 0 V on its output, isn't it?

**Comment by DeepCoreSystem** [comment]
I'll answer my question myself ... In general, any DC/DC boost converter has a leakage path where Vin will be present on Vout, even when the enable pin is pulled low.
For extensive information, see this application note by Texas Instruments:
[Boost Behaviors During Shutdown - Pass Through, Bypass or True Disconnection](https://www.ti.com/lit/pdf/SLVAFO4)

**Comment by SasaKaranovic** [comment]
Hey @DeepCoreSystem 

If you look at the MIC2290 internal block diagram, you will see that SW and OUT have a Schottky diode between them. 
Some regulators will have this built-in internally, but it's also common to have this as an external component.
The EN pin only disables the regulator (switching), however we still have a path from VUSB to OUT via the L1 and built in Schottky diode.

p.s. Personally I think that "leakage" term is often used to describe some undesired/negative/parasitic effect. In this case this path exists by design and it is very much desired. :)

![image](https://github.com/user-attachments/assets/18c13ab3-24aa-4783-9d78-72f9ae17fd80)
